--Q5
WITH PR AS(
SELECT
	F.PRODUCT_ID,
	PRODUCT_DESCRIPTION,
	ROUND(SUM(REVENUE)::NUMERIC, 2) AS TOTAL_REVENUE,
	SUM(QUANTITY) AS UNITS
FROM
	DIM_PRODUCTS D
	JOIN FACT_ORDERS F ON D.PRODUCT_ID = F.PRODUCT_ID
GROUP BY
	F.PRODUCT_ID,
	PRODUCT_DESCRIPTION)

	SELECT *, RANK () OVER (ORDER BY TOTAL_REVENUE DESC) AS RNK
	FROM PR
	ORDER BY RNK LIMIT 10;

--Q6
WITH
PR AS (
SELECT
   PRODUCT_ID,
   ROUND(SUM(REVENUE)::NUMERIC, 2) AS REVENUE
FROM
   FACT_ORDERS
 GROUP BY PRODUCT_ID
   ORDER BY PRODUCT_ID
	)
SELECT
	PRODUCT_ID,
	REVENUE,
	ROUND(REVENUE / SUM(REVENUE) OVER () * 100, 2) AS REVENUE_PCT
FROM
	PR
ORDER BY REVENUE DESC
LIMIT 20