---Q9
WITH LP AS (SELECT CUSTOMER_ID, MAX(INVOICE_DATE) AS LAST_ORDER FROM FACT_ORDERS GROUP BY CUSTOMER_ID)
SELECT CUSTOMER_ID, LAST_ORDER, ('2012-01-01' :: DATE - LAST_ORDER) AS DAYS_INACTIVE,
CASE 
WHEN ('2012-01-01' :: DATE - LAST_ORDER) > 180 THEN 'CHURNED'
WHEN ('2012-01-01' :: DATE - LAST_ORDER) > 90  THEN 'AT RISK'
ELSE 'ACTIVE'
END AS CHURN_STATUS 
FROM LP
ORDER BY DAYS_INACTIVE DESC


---Q10

WITH COHORTS AS (SELECT CUSTOMER_ID, DATE_TRUNC ('MONTH', MIN(INVOICE_DATE)) AS COHORT_MONTH FROM FACT_ORDERS GROUP BY 1),
ACTIVITY AS (SELECT DISTINCT CUSTOMER_ID, DATE_TRUNC ('MONTH', INVOICE_DATE) AS ACTIVE_MONTH FROM FACT_ORDERS)
SELECT C.COHORT_MONTH,
COUNT (DISTINCT C. CUSTOMER_ID) AS COHORT_SIZE,
COUNT (DISTINCT A.CUSTOMER_ID) AS RETURNED,
ROUND(COUNT (DISTINCT A.CUSTOMER_ID) * 100.0 / COUNT (DISTINCT C.CUSTOMER_ID),2) AS RETENTION_PCT FROM COHORTS C  LEFT JOIN ACTIVITY A
ON C.CUSTOMER_ID = A.CUSTOMER_ID
AND A.ACTIVE_MONTH=C.COHORT_MONTH + INTERVAL '1 MONTH' GROUP BY 1 ORDER BY 1

-- COHORT RETENTION KEY FINDINGS:
-- BEST RETENTION : DEC 2010 COHORT → 36.61% RETURNED NEXT MONTH
-- WORST RETENTION: NOV 2011 COHORT → 11.15% (SEASONAL GIFT BUYERS, EXPECTED)
-- DEC 2011       : 0% - DATA LIMITATION, NO JAN 2012 DATA EXISTS
-- INDUSTRY AVG FOR RETAIL: 20-30% MONTH 1 RETENTION
-- OUR AVG (EXCL DEC 2010 AND DEC 2011): ~19% → SLIGHTLY BELOW INDUSTRY
-- RECOMMENDATION: IMPROVE ONBOARDING EXPERIENCE IN FIRST 30 DAYS
-- EVEN +5% RETENTION ACROSS ALL COHORTS = ~200 EXTRA RETURNING CUSTOMERS/MONTH